# Generated by Django 5.0 on 2023-12-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
